FROM python:3.13

RUN apt-get update && apt-get install -y postgresql-client libnss3 libatk-bridge2.0-0 \
    libcups2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 \
    libpango-1.0-0 libcairo2 libasound2 vim && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY attachment_style/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN plotly_get_chrome -y

COPY wait-for-db.py .
COPY entrypoint.sh . 
COPY seed_data.py .
COPY init.sql .

COPY attachment_style/ .

RUN chmod +x /app/entrypoint.sh 

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"]

