"""initial

Revision ID: 33e5a85ee252
Revises: 
Create Date: 2024-11-07 21:10:26.982907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e5a85ee252'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_your_partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('test', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('relationship_status', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('therapy_experience', sa.String(), nullable=False),
    sa.Column('anxious_q1', sa.Integer(), nullable=True),
    sa.Column('anxious_q2', sa.Integer(), nullable=True),
    sa.Column('anxious_q3', sa.Integer(), nullable=True),
    sa.Column('anxious_q4', sa.Integer(), nullable=True),
    sa.Column('anxious_q5', sa.Integer(), nullable=True),
    sa.Column('anxious_q6', sa.Integer(), nullable=True),
    sa.Column('anxious_q7', sa.Integer(), nullable=True),
    sa.Column('anxious_q8', sa.Integer(), nullable=True),
    sa.Column('anxious_q9', sa.Integer(), nullable=True),
    sa.Column('anxious_q10', sa.Integer(), nullable=True),
    sa.Column('anxious_q11', sa.Integer(), nullable=True),
    sa.Column('secure_q1', sa.Integer(), nullable=True),
    sa.Column('secure_q2', sa.Integer(), nullable=True),
    sa.Column('secure_q3', sa.Integer(), nullable=True),
    sa.Column('secure_q4', sa.Integer(), nullable=True),
    sa.Column('secure_q5', sa.Integer(), nullable=True),
    sa.Column('secure_q6', sa.Integer(), nullable=True),
    sa.Column('secure_q7', sa.Integer(), nullable=True),
    sa.Column('secure_q8', sa.Integer(), nullable=True),
    sa.Column('secure_q9', sa.Integer(), nullable=True),
    sa.Column('secure_q10', sa.Integer(), nullable=True),
    sa.Column('secure_q11', sa.Integer(), nullable=True),
    sa.Column('avoidant_q1', sa.Integer(), nullable=True),
    sa.Column('avoidant_q2', sa.Integer(), nullable=True),
    sa.Column('avoidant_q3', sa.Integer(), nullable=True),
    sa.Column('avoidant_q4', sa.Integer(), nullable=True),
    sa.Column('avoidant_q5', sa.Integer(), nullable=True),
    sa.Column('avoidant_q6', sa.Integer(), nullable=True),
    sa.Column('avoidant_q7', sa.Integer(), nullable=True),
    sa.Column('avoidant_q8', sa.Integer(), nullable=True),
    sa.Column('avoidant_q9', sa.Integer(), nullable=True),
    sa.Column('avoidant_q10', sa.Integer(), nullable=True),
    sa.Column('avoidant_q11', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_yourself',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('test', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('relationship_status', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('therapy_experience', sa.String(), nullable=False),
    sa.Column('anxious_q1', sa.Integer(), nullable=True),
    sa.Column('anxious_q2', sa.Integer(), nullable=True),
    sa.Column('anxious_q3', sa.Integer(), nullable=True),
    sa.Column('anxious_q4', sa.Integer(), nullable=True),
    sa.Column('anxious_q5', sa.Integer(), nullable=True),
    sa.Column('anxious_q6', sa.Integer(), nullable=True),
    sa.Column('anxious_q7', sa.Integer(), nullable=True),
    sa.Column('anxious_q8', sa.Integer(), nullable=True),
    sa.Column('anxious_q9', sa.Integer(), nullable=True),
    sa.Column('anxious_q10', sa.Integer(), nullable=True),
    sa.Column('anxious_q11', sa.Integer(), nullable=True),
    sa.Column('anxious_q12', sa.Integer(), nullable=True),
    sa.Column('anxious_q13', sa.Integer(), nullable=True),
    sa.Column('anxious_q14', sa.Integer(), nullable=True),
    sa.Column('secure_q1', sa.Integer(), nullable=True),
    sa.Column('secure_q2', sa.Integer(), nullable=True),
    sa.Column('secure_q3', sa.Integer(), nullable=True),
    sa.Column('secure_q4', sa.Integer(), nullable=True),
    sa.Column('secure_q5', sa.Integer(), nullable=True),
    sa.Column('secure_q6', sa.Integer(), nullable=True),
    sa.Column('secure_q7', sa.Integer(), nullable=True),
    sa.Column('secure_q8', sa.Integer(), nullable=True),
    sa.Column('secure_q9', sa.Integer(), nullable=True),
    sa.Column('secure_q10', sa.Integer(), nullable=True),
    sa.Column('secure_q11', sa.Integer(), nullable=True),
    sa.Column('secure_q12', sa.Integer(), nullable=True),
    sa.Column('secure_q13', sa.Integer(), nullable=True),
    sa.Column('secure_q14', sa.Integer(), nullable=True),
    sa.Column('avoidant_q1', sa.Integer(), nullable=True),
    sa.Column('avoidant_q2', sa.Integer(), nullable=True),
    sa.Column('avoidant_q3', sa.Integer(), nullable=True),
    sa.Column('avoidant_q4', sa.Integer(), nullable=True),
    sa.Column('avoidant_q5', sa.Integer(), nullable=True),
    sa.Column('avoidant_q6', sa.Integer(), nullable=True),
    sa.Column('avoidant_q7', sa.Integer(), nullable=True),
    sa.Column('avoidant_q8', sa.Integer(), nullable=True),
    sa.Column('avoidant_q9', sa.Integer(), nullable=True),
    sa.Column('avoidant_q10', sa.Integer(), nullable=True),
    sa.Column('avoidant_q11', sa.Integer(), nullable=True),
    sa.Column('avoidant_q12', sa.Integer(), nullable=True),
    sa.Column('avoidant_q13', sa.Integer(), nullable=True),
    sa.Column('avoidant_q14', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_yourself')
    op.drop_table('test_your_partner')
    # ### end Alembic commands ###
