"""increment_question_numbers

Revision ID: 3d4056211643
Revises: 7cffe761ac3f
Create Date: 2025-06-22 22:03:19.325229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4056211643'
down_revision: Union[str, None] = '7cffe761ac3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_yourself', sa.Column('avoidant_q18', sa.Integer(), nullable=True))
    op.drop_column('test_yourself', 'avoidant_q0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_yourself', sa.Column('avoidant_q0', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('test_yourself', 'avoidant_q18')
    # ### end Alembic commands ###
