"""initial

Revision ID: 776a7a509d69
Revises: 
Create Date: 2025-08-04 18:10:01.201291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776a7a509d69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assess_others',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('test', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('relationship_status', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('therapy_experience', sa.String(), nullable=False),
    sa.Column('anxious_q1', sa.Integer(), nullable=True),
    sa.Column('anxious_q2', sa.Integer(), nullable=True),
    sa.Column('anxious_q3', sa.Integer(), nullable=True),
    sa.Column('anxious_q4', sa.Integer(), nullable=True),
    sa.Column('anxious_q5', sa.Integer(), nullable=True),
    sa.Column('anxious_q6', sa.Integer(), nullable=True),
    sa.Column('anxious_q7', sa.Integer(), nullable=True),
    sa.Column('anxious_q8', sa.Integer(), nullable=True),
    sa.Column('anxious_q9', sa.Integer(), nullable=True),
    sa.Column('anxious_q10', sa.Integer(), nullable=True),
    sa.Column('anxious_q11', sa.Integer(), nullable=True),
    sa.Column('secure_q1', sa.Integer(), nullable=True),
    sa.Column('secure_q2', sa.Integer(), nullable=True),
    sa.Column('secure_q3', sa.Integer(), nullable=True),
    sa.Column('secure_q4', sa.Integer(), nullable=True),
    sa.Column('secure_q5', sa.Integer(), nullable=True),
    sa.Column('secure_q6', sa.Integer(), nullable=True),
    sa.Column('secure_q7', sa.Integer(), nullable=True),
    sa.Column('secure_q8', sa.Integer(), nullable=True),
    sa.Column('secure_q9', sa.Integer(), nullable=True),
    sa.Column('secure_q10', sa.Integer(), nullable=True),
    sa.Column('secure_q11', sa.Integer(), nullable=True),
    sa.Column('avoidant_q1', sa.Integer(), nullable=True),
    sa.Column('avoidant_q2', sa.Integer(), nullable=True),
    sa.Column('avoidant_q3', sa.Integer(), nullable=True),
    sa.Column('avoidant_q4', sa.Integer(), nullable=True),
    sa.Column('avoidant_q5', sa.Integer(), nullable=True),
    sa.Column('avoidant_q6', sa.Integer(), nullable=True),
    sa.Column('avoidant_q7', sa.Integer(), nullable=True),
    sa.Column('avoidant_q8', sa.Integer(), nullable=True),
    sa.Column('avoidant_q9', sa.Integer(), nullable=True),
    sa.Column('avoidant_q10', sa.Integer(), nullable=True),
    sa.Column('avoidant_q11', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assess_yourself',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('test', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('relationship_status', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('therapy_experience', sa.String(), nullable=False),
    sa.Column('anxious_q1', sa.Integer(), nullable=True),
    sa.Column('anxious_q2', sa.Integer(), nullable=True),
    sa.Column('anxious_q3', sa.Integer(), nullable=True),
    sa.Column('anxious_q4', sa.Integer(), nullable=True),
    sa.Column('anxious_q5', sa.Integer(), nullable=True),
    sa.Column('anxious_q6', sa.Integer(), nullable=True),
    sa.Column('anxious_q7', sa.Integer(), nullable=True),
    sa.Column('anxious_q8', sa.Integer(), nullable=True),
    sa.Column('anxious_q9', sa.Integer(), nullable=True),
    sa.Column('anxious_q10', sa.Integer(), nullable=True),
    sa.Column('anxious_q11', sa.Integer(), nullable=True),
    sa.Column('anxious_q12', sa.Integer(), nullable=True),
    sa.Column('anxious_q13', sa.Integer(), nullable=True),
    sa.Column('anxious_q14', sa.Integer(), nullable=True),
    sa.Column('anxious_q15', sa.Integer(), nullable=True),
    sa.Column('anxious_q16', sa.Integer(), nullable=True),
    sa.Column('anxious_q17', sa.Integer(), nullable=True),
    sa.Column('anxious_q18', sa.Integer(), nullable=True),
    sa.Column('avoidant_q1', sa.Integer(), nullable=True),
    sa.Column('avoidant_q2', sa.Integer(), nullable=True),
    sa.Column('avoidant_q3', sa.Integer(), nullable=True),
    sa.Column('avoidant_q4', sa.Integer(), nullable=True),
    sa.Column('avoidant_q5', sa.Integer(), nullable=True),
    sa.Column('avoidant_q6', sa.Integer(), nullable=True),
    sa.Column('avoidant_q7', sa.Integer(), nullable=True),
    sa.Column('avoidant_q8', sa.Integer(), nullable=True),
    sa.Column('avoidant_q9', sa.Integer(), nullable=True),
    sa.Column('avoidant_q10', sa.Integer(), nullable=True),
    sa.Column('avoidant_q11', sa.Integer(), nullable=True),
    sa.Column('avoidant_q12', sa.Integer(), nullable=True),
    sa.Column('avoidant_q13', sa.Integer(), nullable=True),
    sa.Column('avoidant_q14', sa.Integer(), nullable=True),
    sa.Column('avoidant_q15', sa.Integer(), nullable=True),
    sa.Column('avoidant_q16', sa.Integer(), nullable=True),
    sa.Column('avoidant_q17', sa.Integer(), nullable=True),
    sa.Column('avoidant_q18', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assess_yourself')
    op.drop_table('assess_others')
    # ### end Alembic commands ###
