"""swich_to_ecr_r

Revision ID: 7cffe761ac3f
Revises: 33e5a85ee252
Create Date: 2025-06-22 21:44:35.596533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cffe761ac3f'
down_revision: Union[str, None] = '33e5a85ee252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_yourself', sa.Column('avoidant_q0', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q15', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q16', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q17', sa.Integer(), nullable=True))
    op.drop_column('test_yourself', 'anxious_q2')
    op.drop_column('test_yourself', 'anxious_q11')
    op.drop_column('test_yourself', 'anxious_q6')
    op.drop_column('test_yourself', 'secure_q13')
    op.drop_column('test_yourself', 'secure_q5')
    op.drop_column('test_yourself', 'anxious_q3')
    op.drop_column('test_yourself', 'secure_q4')
    op.drop_column('test_yourself', 'secure_q14')
    op.drop_column('test_yourself', 'secure_q7')
    op.drop_column('test_yourself', 'secure_q10')
    op.drop_column('test_yourself', 'secure_q9')
    op.drop_column('test_yourself', 'secure_q6')
    op.drop_column('test_yourself', 'secure_q8')
    op.drop_column('test_yourself', 'anxious_q8')
    op.drop_column('test_yourself', 'anxious_q13')
    op.drop_column('test_yourself', 'anxious_q14')
    op.drop_column('test_yourself', 'anxious_q10')
    op.drop_column('test_yourself', 'secure_q3')
    op.drop_column('test_yourself', 'secure_q2')
    op.drop_column('test_yourself', 'secure_q1')
    op.drop_column('test_yourself', 'anxious_q12')
    op.drop_column('test_yourself', 'anxious_q7')
    op.drop_column('test_yourself', 'secure_q12')
    op.drop_column('test_yourself', 'anxious_q1')
    op.drop_column('test_yourself', 'anxious_q5')
    op.drop_column('test_yourself', 'anxious_q9')
    op.drop_column('test_yourself', 'secure_q11')
    op.drop_column('test_yourself', 'anxious_q4')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_yourself', sa.Column('anxious_q4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q11', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q9', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q12', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q7', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q12', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q10', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q14', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q13', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q8', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q8', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q6', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q9', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q10', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q7', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q14', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q13', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q6', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q11', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('test_yourself', 'avoidant_q17')
    op.drop_column('test_yourself', 'avoidant_q16')
    op.drop_column('test_yourself', 'avoidant_q15')
    op.drop_column('test_yourself', 'avoidant_q0')
    # ### end Alembic commands ###
