"""correct_avoidant_to_anxious

Revision ID: b96b619b0be0
Revises: 3d4056211643
Create Date: 2025-06-22 22:04:49.879302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96b619b0be0'
down_revision: Union[str, None] = '3d4056211643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_yourself', sa.Column('anxious_q1', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q2', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q3', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q4', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q5', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q6', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q7', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q8', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q9', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q10', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q11', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q12', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q13', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q14', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q15', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q16', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q17', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('anxious_q18', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_yourself', 'anxious_q18')
    op.drop_column('test_yourself', 'anxious_q17')
    op.drop_column('test_yourself', 'anxious_q16')
    op.drop_column('test_yourself', 'anxious_q15')
    op.drop_column('test_yourself', 'anxious_q14')
    op.drop_column('test_yourself', 'anxious_q13')
    op.drop_column('test_yourself', 'anxious_q12')
    op.drop_column('test_yourself', 'anxious_q11')
    op.drop_column('test_yourself', 'anxious_q10')
    op.drop_column('test_yourself', 'anxious_q9')
    op.drop_column('test_yourself', 'anxious_q8')
    op.drop_column('test_yourself', 'anxious_q7')
    op.drop_column('test_yourself', 'anxious_q6')
    op.drop_column('test_yourself', 'anxious_q5')
    op.drop_column('test_yourself', 'anxious_q4')
    op.drop_column('test_yourself', 'anxious_q3')
    op.drop_column('test_yourself', 'anxious_q2')
    op.drop_column('test_yourself', 'anxious_q1')
    # ### end Alembic commands ###
