"""add aggregated scores

Revision ID: d1d302ea732f
Revises: 776a7a509d69
Create Date: 2025-08-07 17:07:03.757916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d302ea732f'
down_revision: Union[str, None] = '776a7a509d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assess_others', sa.Column('anxious_score', sa.Integer(), nullable=True))
    op.add_column('assess_others', sa.Column('avoidant_score', sa.Integer(), nullable=True))
    op.add_column('assess_others', sa.Column('secure_score', sa.Integer(), nullable=True))
    op.add_column('assess_yourself', sa.Column('anxious_score', sa.Integer(), nullable=True))
    op.add_column('assess_yourself', sa.Column('avoidant_score', sa.Integer(), nullable=True))
    op.add_column('assess_yourself', sa.Column('secure_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assess_yourself', 'secure_score')
    op.drop_column('assess_yourself', 'avoidant_score')
    op.drop_column('assess_yourself', 'anxious_score')
    op.drop_column('assess_others', 'secure_score')
    op.drop_column('assess_others', 'avoidant_score')
    op.drop_column('assess_others', 'anxious_score')
    # ### end Alembic commands ###
