"""add_test_yourself

Revision ID: f64d721de543
Revises: 
Create Date: 2024-07-14 19:03:17.150331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64d721de543'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_yourself',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('q1', sa.Float(), nullable=False),
    sa.Column('q2', sa.Float(), nullable=False),
    sa.Column('q3', sa.Float(), nullable=False),
    sa.Column('q4', sa.Float(), nullable=False),
    sa.Column('q5', sa.Float(), nullable=False),
    sa.Column('q6', sa.Float(), nullable=False),
    sa.Column('q7', sa.Float(), nullable=False),
    sa.Column('q8', sa.Float(), nullable=False),
    sa.Column('q9', sa.Float(), nullable=False),
    sa.Column('q10', sa.Float(), nullable=False),
    sa.Column('q11', sa.Float(), nullable=False),
    sa.Column('q12', sa.Float(), nullable=False),
    sa.Column('q13', sa.Float(), nullable=False),
    sa.Column('q14', sa.Float(), nullable=False),
    sa.Column('q15', sa.Float(), nullable=False),
    sa.Column('q16', sa.Float(), nullable=False),
    sa.Column('q17', sa.Float(), nullable=False),
    sa.Column('q18', sa.Float(), nullable=False),
    sa.Column('q19', sa.Float(), nullable=False),
    sa.Column('q20', sa.Float(), nullable=False),
    sa.Column('q21', sa.Float(), nullable=False),
    sa.Column('q22', sa.Float(), nullable=False),
    sa.Column('q23', sa.Float(), nullable=False),
    sa.Column('q24', sa.Float(), nullable=False),
    sa.Column('q25', sa.Float(), nullable=False),
    sa.Column('q26', sa.Float(), nullable=False),
    sa.Column('q27', sa.Float(), nullable=False),
    sa.Column('q28', sa.Float(), nullable=False),
    sa.Column('q29', sa.Float(), nullable=False),
    sa.Column('q30', sa.Float(), nullable=False),
    sa.Column('q31', sa.Float(), nullable=False),
    sa.Column('q32', sa.Float(), nullable=False),
    sa.Column('q33', sa.Float(), nullable=False),
    sa.Column('q34', sa.Float(), nullable=False),
    sa.Column('q35', sa.Float(), nullable=False),
    sa.Column('q36', sa.Float(), nullable=False),
    sa.Column('q37', sa.Float(), nullable=False),
    sa.Column('q38', sa.Float(), nullable=False),
    sa.Column('q39', sa.Float(), nullable=False),
    sa.Column('q40', sa.Float(), nullable=False),
    sa.Column('q41', sa.Float(), nullable=False),
    sa.Column('q42', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_yourself')
    # ### end Alembic commands ###
