"""questions numbering & optional

Revision ID: 242c4b40161c
Revises: 320c80f44faa
Create Date: 2024-10-11 15:18:11.569731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242c4b40161c'
down_revision: Union[str, None] = '320c80f44faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_your_partner', sa.Column('secure_q1', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q2', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q3', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q4', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q5', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q6', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q7', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q8', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q9', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q10', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('secure_q11', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q1', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q2', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q3', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q4', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q5', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q6', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q7', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q8', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q9', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q10', sa.Integer(), nullable=True))
    op.add_column('test_your_partner', sa.Column('avoidant_q11', sa.Integer(), nullable=True))
    op.alter_column('test_your_partner', 'anxious_q1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q3',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q4',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q5',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q6',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q7',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q8',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q9',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q10',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_your_partner', 'anxious_q11',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('test_your_partner', 'secure_q13')
    op.drop_column('test_your_partner', 'avoidant_q33')
    op.drop_column('test_your_partner', 'secure_q16')
    op.drop_column('test_your_partner', 'avoidant_q24')
    op.drop_column('test_your_partner', 'secure_q20')
    op.drop_column('test_your_partner', 'avoidant_q27')
    op.drop_column('test_your_partner', 'avoidant_q26')
    op.drop_column('test_your_partner', 'avoidant_q23')
    op.drop_column('test_your_partner', 'avoidant_q31')
    op.drop_column('test_your_partner', 'secure_q22')
    op.drop_column('test_your_partner', 'secure_q14')
    op.drop_column('test_your_partner', 'secure_q19')
    op.drop_column('test_your_partner', 'secure_q21')
    op.drop_column('test_your_partner', 'secure_q17')
    op.drop_column('test_your_partner', 'secure_q18')
    op.drop_column('test_your_partner', 'avoidant_q28')
    op.drop_column('test_your_partner', 'secure_q12')
    op.drop_column('test_your_partner', 'avoidant_q29')
    op.drop_column('test_your_partner', 'avoidant_q25')
    op.drop_column('test_your_partner', 'avoidant_q32')
    op.drop_column('test_your_partner', 'avoidant_q30')
    op.drop_column('test_your_partner', 'secure_q15')
    op.add_column('test_yourself', sa.Column('secure_q1', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q2', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q3', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q4', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q5', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q6', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q7', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q8', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q9', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q10', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q11', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q12', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q13', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('secure_q14', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q1', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q2', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q3', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q4', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q5', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q6', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q7', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q8', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q9', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q10', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q11', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q12', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q13', sa.Integer(), nullable=True))
    op.add_column('test_yourself', sa.Column('avoidant_q14', sa.Integer(), nullable=True))
    op.alter_column('test_yourself', 'anxious_q1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q3',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q4',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q5',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q6',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q7',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q8',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q9',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q10',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q11',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q12',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q13',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_yourself', 'anxious_q14',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('test_yourself', 'avoidant_q33')
    op.drop_column('test_yourself', 'avoidant_q34')
    op.drop_column('test_yourself', 'avoidant_q40')
    op.drop_column('test_yourself', 'secure_q26')
    op.drop_column('test_yourself', 'avoidant_q35')
    op.drop_column('test_yourself', 'secure_q16')
    op.drop_column('test_yourself', 'secure_q20')
    op.drop_column('test_yourself', 'secure_q27')
    op.drop_column('test_yourself', 'avoidant_q37')
    op.drop_column('test_yourself', 'avoidant_q42')
    op.drop_column('test_yourself', 'avoidant_q31')
    op.drop_column('test_yourself', 'avoidant_q41')
    op.drop_column('test_yourself', 'secure_q22')
    op.drop_column('test_yourself', 'secure_q19')
    op.drop_column('test_yourself', 'secure_q21')
    op.drop_column('test_yourself', 'secure_q23')
    op.drop_column('test_yourself', 'secure_q17')
    op.drop_column('test_yourself', 'secure_q28')
    op.drop_column('test_yourself', 'secure_q18')
    op.drop_column('test_yourself', 'avoidant_q38')
    op.drop_column('test_yourself', 'avoidant_q29')
    op.drop_column('test_yourself', 'avoidant_q36')
    op.drop_column('test_yourself', 'secure_q24')
    op.drop_column('test_yourself', 'secure_q25')
    op.drop_column('test_yourself', 'avoidant_q39')
    op.drop_column('test_yourself', 'avoidant_q32')
    op.drop_column('test_yourself', 'avoidant_q30')
    op.drop_column('test_yourself', 'secure_q15')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_yourself', sa.Column('secure_q15', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q30', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q32', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q39', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q25', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q24', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q36', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q29', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q38', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q18', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q28', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q17', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q23', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q21', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q19', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q22', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q41', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q31', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q42', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q37', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q27', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q20', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q16', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q35', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('secure_q26', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q40', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q34', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_yourself', sa.Column('avoidant_q33', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('test_yourself', 'anxious_q14',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q13',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q12',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q11',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q10',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q9',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q8',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q7',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q6',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q5',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q4',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q3',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_yourself', 'anxious_q1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('test_yourself', 'avoidant_q14')
    op.drop_column('test_yourself', 'avoidant_q13')
    op.drop_column('test_yourself', 'avoidant_q12')
    op.drop_column('test_yourself', 'avoidant_q11')
    op.drop_column('test_yourself', 'avoidant_q10')
    op.drop_column('test_yourself', 'avoidant_q9')
    op.drop_column('test_yourself', 'avoidant_q8')
    op.drop_column('test_yourself', 'avoidant_q7')
    op.drop_column('test_yourself', 'avoidant_q6')
    op.drop_column('test_yourself', 'avoidant_q5')
    op.drop_column('test_yourself', 'avoidant_q4')
    op.drop_column('test_yourself', 'avoidant_q3')
    op.drop_column('test_yourself', 'avoidant_q2')
    op.drop_column('test_yourself', 'avoidant_q1')
    op.drop_column('test_yourself', 'secure_q14')
    op.drop_column('test_yourself', 'secure_q13')
    op.drop_column('test_yourself', 'secure_q12')
    op.drop_column('test_yourself', 'secure_q11')
    op.drop_column('test_yourself', 'secure_q10')
    op.drop_column('test_yourself', 'secure_q9')
    op.drop_column('test_yourself', 'secure_q8')
    op.drop_column('test_yourself', 'secure_q7')
    op.drop_column('test_yourself', 'secure_q6')
    op.drop_column('test_yourself', 'secure_q5')
    op.drop_column('test_yourself', 'secure_q4')
    op.drop_column('test_yourself', 'secure_q3')
    op.drop_column('test_yourself', 'secure_q2')
    op.drop_column('test_yourself', 'secure_q1')
    op.add_column('test_your_partner', sa.Column('secure_q15', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q30', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q32', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q25', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q29', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q12', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q28', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q18', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q17', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q21', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q19', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q14', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q22', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q31', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q23', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q26', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q27', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q20', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q24', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q16', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('avoidant_q33', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('test_your_partner', sa.Column('secure_q13', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('test_your_partner', 'anxious_q11',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q10',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q9',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q8',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q7',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q6',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q5',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q4',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q3',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_your_partner', 'anxious_q1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('test_your_partner', 'avoidant_q11')
    op.drop_column('test_your_partner', 'avoidant_q10')
    op.drop_column('test_your_partner', 'avoidant_q9')
    op.drop_column('test_your_partner', 'avoidant_q8')
    op.drop_column('test_your_partner', 'avoidant_q7')
    op.drop_column('test_your_partner', 'avoidant_q6')
    op.drop_column('test_your_partner', 'avoidant_q5')
    op.drop_column('test_your_partner', 'avoidant_q4')
    op.drop_column('test_your_partner', 'avoidant_q3')
    op.drop_column('test_your_partner', 'avoidant_q2')
    op.drop_column('test_your_partner', 'avoidant_q1')
    op.drop_column('test_your_partner', 'secure_q11')
    op.drop_column('test_your_partner', 'secure_q10')
    op.drop_column('test_your_partner', 'secure_q9')
    op.drop_column('test_your_partner', 'secure_q8')
    op.drop_column('test_your_partner', 'secure_q7')
    op.drop_column('test_your_partner', 'secure_q6')
    op.drop_column('test_your_partner', 'secure_q5')
    op.drop_column('test_your_partner', 'secure_q4')
    op.drop_column('test_your_partner', 'secure_q3')
    op.drop_column('test_your_partner', 'secure_q2')
    op.drop_column('test_your_partner', 'secure_q1')
    # ### end Alembic commands ###
