"""add test column

Revision ID: 320c80f44faa
Revises: 7fbca9aa75af
Create Date: 2024-09-28 14:40:29.185142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320c80f44faa'
down_revision: Union[str, None] = '7fbca9aa75af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_your_partner', sa.Column('test', sa.Boolean(), nullable=False))
    op.add_column('test_yourself', sa.Column('test', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_yourself', 'test')
    op.drop_column('test_your_partner', 'test')
    # ### end Alembic commands ###
