import re
from datetime import datetime
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass

class TestYourself(Base):
    __tablename__ = "test_yourself"

    id: Mapped[int] = mapped_column(primary_key=True)
    timestamp: Mapped[datetime]
    age: Mapped[int]
    relationship_status: Mapped[str]
    gender: Mapped[str]
    therapy_experience: Mapped[str]
    q1: Mapped[int]
    q2: Mapped[int]
    q3: Mapped[int]
    q4: Mapped[int]
    q5: Mapped[int]
    q6: Mapped[int]
    q7: Mapped[int]
    q8: Mapped[int]
    q9: Mapped[int]
    q10: Mapped[int]
    q11: Mapped[int]
    q12: Mapped[int]
    q13: Mapped[int]
    q14: Mapped[int]
    q15: Mapped[int]
    q16: Mapped[int]
    q17: Mapped[int]
    q18: Mapped[int]
    q19: Mapped[int]
    q20: Mapped[int]
    q21: Mapped[int]
    q22: Mapped[int]
    q23: Mapped[int]
    q24: Mapped[int]
    q25: Mapped[int]
    q26: Mapped[int]
    q27: Mapped[int]
    q28: Mapped[int]
    q29: Mapped[int]
    q30: Mapped[int]
    q31: Mapped[int]
    q32: Mapped[int]
    q33: Mapped[int]
    q34: Mapped[int]
    q35: Mapped[int]
    q36: Mapped[int]
    q37: Mapped[int]
    q38: Mapped[int]
    q39: Mapped[int]
    q40: Mapped[int]
    q41: Mapped[int]
    q42: Mapped[int]

class TestYourPartner(Base):
    __tablename__ = "test_your_partner"

    id: Mapped[int] = mapped_column(primary_key=True)
    timestamp: Mapped[datetime]
    age: Mapped[int]
    relationship_status: Mapped[str]
    gender: Mapped[str]
    therapy_experience: Mapped[str]
    q1: Mapped[int]
    q2: Mapped[int]
    q3: Mapped[int]
    q4: Mapped[int]
    q5: Mapped[int]
    q6: Mapped[int]
    q7: Mapped[int]
    q8: Mapped[int]
    q9: Mapped[int]
    q10: Mapped[int]
    q11: Mapped[int]
    q12: Mapped[int]
    q13: Mapped[int]
    q14: Mapped[int]
    q15: Mapped[int]
    q16: Mapped[int]
    q17: Mapped[int]
    q18: Mapped[int]
    q19: Mapped[int]
    q20: Mapped[int]
    q21: Mapped[int]
    q22: Mapped[int]
    q23: Mapped[int]
    q24: Mapped[int]
    q25: Mapped[int]
    q26: Mapped[int]
    q27: Mapped[int]
    q28: Mapped[int]
    q29: Mapped[int]
    q30: Mapped[int]
    q31: Mapped[int]
    q32: Mapped[int]
    q33: Mapped[int]
